name: Build Scarlet Skips

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install bannertool and makerom
        run: |
          wget https://github.com/diasurgical/bannertool/releases/download/1.2.0/bannertool.zip
          unzip -j bannertool.zip linux-x86_64/bannertool -d /opt/devkitpro/tools/bin

          wget https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18/makerom-v0.18-ubuntu_x86_64.zip
          unzip -j makerom-v0.18-ubuntu_x86_64.zip makerom -d /opt/devkitpro/tools/bin

          chmod a+x /opt/devkitpro/tools/bin/makerom
          chmod a+x /opt/devkitpro/tools/bin/bannertool

      - name: Build Scarlet Skips
        run: make

      - name: Upload Scarlet Skips
        uses: actions/upload-artifact@v4
        with:
          name: scarlet-skips
          path: |
            ScarletSkips.cia
            ScarletSkips.3dsx
            ScarletSkips.smdh
